
spring:
  application:
    name: helloserver
  datasource:
    username: root
    password: pass@word1  
    
server:
  port: 8071
  

  
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
      
      
      
      
      
      
      